# Generated by Django 3.2.11 on 2022-01-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_info', '0002_remove_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
    ]
