# Generated by Django 3.2.11 on 2022-01-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, default='', max_length=255, verbose_name='手机')),
                ('wechat_name', models.CharField(blank=True, default='', max_length=255, verbose_name='微信昵称')),
                ('driver_license', models.CharField(blank=True, default='', max_length=255, verbose_name='驾驶证')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='客户来源')),
                ('type', models.CharField(blank=True, default='', max_length=255, verbose_name='客户类型')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='', max_length=255, verbose_name='性别')),
                ('birthday', models.CharField(blank=True, default='', max_length=255, verbose_name='生日')),
                ('identity', models.CharField(blank=True, default='', max_length=255, verbose_name='身份证')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('allowable_amount', models.CharField(blank=True, default='', max_length=255, verbose_name='允许挂账金额')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='单位')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('employee_bonus', models.CharField(blank=True, default='', max_length=255, verbose_name='分红员工')),
                ('car_type', models.CharField(blank=True, default='', max_length=255, verbose_name='车辆型号')),
                ('licence_plate', models.CharField(blank=True, default='', max_length=255, verbose_name='车牌')),
                ('belonger', models.CharField(blank=True, default='', max_length=255, verbose_name='所有人')),
                ('belonger_address', models.CharField(blank=True, default='', max_length=255, verbose_name='所有人地址')),
                ('last_maintenance_mileage', models.CharField(blank=True, default='', max_length=255, verbose_name='上次保养里程')),
                ('next_maintenance_mileage', models.CharField(blank=True, default='', max_length=255, verbose_name='下次保养里程')),
                ('driving_license', models.CharField(blank=True, default='', max_length=255, verbose_name='行驶证')),
                ('chassis_number', models.CharField(blank=True, default='', max_length=255, verbose_name='车架号')),
                ('engine_model', models.CharField(blank=True, default='', max_length=255, verbose_name='发动机型号')),
                ('car_purchase_time', models.CharField(blank=True, default='', max_length=255, verbose_name='购车时间')),
                ('expiration_of_annual_inspection_date', models.CharField(blank=True, default='', max_length=255, verbose_name='年检到期')),
                ('insurance_company', models.CharField(blank=True, default='', max_length=255, verbose_name='保险公司')),
                ('expiration_of_insurance_date', models.CharField(blank=True, default='', max_length=255, verbose_name='保险到期')),
                ('car_price', models.CharField(blank=True, default='', max_length=255, verbose_name='车价')),
                ('displacement', models.CharField(blank=True, default='', max_length=255, verbose_name='排量')),
                ('brand_model', models.CharField(blank=True, default='', max_length=255, verbose_name='厂牌型号')),
                ('colour', models.CharField(blank=True, default='', max_length=255, verbose_name='颜色')),
                ('engine_number', models.CharField(blank=True, default='', max_length=255, verbose_name='发动机号')),
                ('cumulative_consumption', models.CharField(blank=True, default='', max_length=255, verbose_name='累计消费')),
                ('days_before_arrival', models.CharField(blank=True, default='', max_length=255, verbose_name='未到店天数')),
                ('total_number_of_arrivals', models.CharField(blank=True, default='', max_length=255, verbose_name='总到店次数')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
